### ISSUE TITLE
Custom fonts started doesn't render custom fonts

### ISSUE THREAD

**Issue by SleeplessByte** [nandorojo/solito#151]
The custom fonts starter (https://custom-font.example.solito.dev/) does _load_ the Font files (can be seen in the network tab) but doesn't actually initialize them, with a warning in the console about the fonts not being used and the rendered font using Segoe UI and Times New Roman respectively.

![image](https://user-images.githubusercontent.com/1964376/189550186-6211a6b2-b5b2-4d2d-a303-0738d7119aa1.png)

**Comment by jonsherrard** [comment]
This is due to a type on https://github.com/nandorojo/solito/blob/master/example-monorepos/with-custom-font/apps/next/pages/_document.tsx#L14

You can update `url` to `src` as per the `font-face` spec and they will start working. Fernando probably had Inter installed locally so it didn't show up. :)

**Comment by nandorojo** [comment]
Good catch! https://github.com/nandorojo/solito/commit/5a3761f2aae1006b45578b2142911159a5459653
