### ISSUE TITLE
[question] Next.js SSG is not working correctly with Solito Example Monorepo ?

### ISSUE THREAD

**Issue by pokuwagata** [nandorojo/solito#34]
## Problem

Next.js SSG can not export static HTML correctly in Solito Example Monorepo.

## To reproduce

1. `$ npx create-solito-app@latest my-solito-app`
2. `$ next build && next export`
3. `$cat out/index.html`

expected

```
<body>
    <div id="__next">
      <div style="flex: 1">
        <div>some HTML...</div>
      </div>
    </div>
...
```

but I got below.

```
<body>
    <div id="__next" data-reactroot=""></div>
    <script id="__NEXT_DATA__" type="application/json">
...
```

- <https://github.com/pokuwagata/solito-expo-nextjs-navigation-sample>

## Question

- Is Next.js SSG fully supported with Solito?
- How can I export static HTML with Solito?

**Comment by nandorojo** [comment]
So…this is a general problem with React Native Web + SSR. 

You can either:

1. enable SSR
2. use responsive design

but you can’t do both. because of react’s hydration, you can’t do both. If you want to enable 1, pass `ssr={false}` to the DripsyProvider.

I have written about SSR at great length on the Dripsy issues and PRs. If you google React Native Web SSR, responsive design or classname support, you’ll find me talking about it. I wish I had a better answer. There are some hacks people have used, but I haven’t found them satisfactory to use. Alternatively you could use tamagui for responsive design systems. But there’s a lot of magic under the hood there compared to Dripsy, and more boilerplate to use it.

hope that helps. when i’m on my computer tomorrow I can link to some issues if you’d like.

**Comment by pokuwagata** [comment]
Thanks for quick answer. enable SSR resolved my issue.
