### ISSUE TITLE
Rewriting the url using the `as` parameter clears params on native.

### ISSUE THREAD

**Issue by crewtaylorfd** [nandorojo/solito#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

If I do the following 

```ts
const router = useRouter()
router.push({
      pathname: `/video/${id}`,
      query: params,
}, `/video/${id}`)
```

The params are not accessible on native. If I remove the `as` parameter, the second argument to `router.push()`, in this case it is `/video/${id}`,  the params come back. 

### Expected Behavior

If I pass in an `as` parameter to the `push` function the params should still be accessible on native

### Steps To Reproduce

1. Create a solito project
2. Use the push function with the `as` parameter to rewrite the URL. 
3. Check the params on native and see if you get you query params you passed into the `push` function

### Versions

```markdown
- Solito:
- Next.js:
- Expo:
- React Native:
```

**Comment by nandorojo** [comment]
The asPath will be used on native. Is there a reason to not pass the asPath and have that be what it links to?

**Comment by crewtaylorfd** [comment]
> The asPath will be used on native. Is there a reason to not pass the asPath and have that be what it links to?

I would like to rewrite the url to hide the query params when on web. That is why I am passing the as argument here to write the url to just the pathname.

**Comment by nandorojo** [comment]
You could pass asPath on web only

**Comment by nandorojo** [comment]
The as path in my mind is where the native app should go. Because if you want to jump from the website into the app, the browser is going to use what’s in the actual address bar. Hiding params is a rare case on web, typically reserved for modals on top of list pages. And in that case the info should be shown to the user.

It might be worth asking if hiding the query params is what you actually should be doing here (though I don’t know the use case)
