### ISSUE TITLE
Upgrade to Expo SDK 46 / Next 12.2

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/solito#99]
Would be great if someone could PR the example app to upgrade these. Expo and Next could each have their own PR. Next 12.2 might be less urgent since next transpile modules might not work for it yet (?)

**Comment by jonsherrard** [comment]
I tried to take a stab at this.

First error I get is that `Constants` are deprecated in 45:

`Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45. `

Apparently deep in there package.json tree there is a conflicting expo-linking package dependency.

Before I can even get into that, (preface: i don't use yarn), I can't even try and install a specific version of `expo-linking` because i run into:

`Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` whenever I run yarn:

This is likely due to a circular dependency area which Yarn doesn't detect: https://stackoverflow.com/questions/56341283/yarn-build-crashes-error-javascript-heap-out-of-memory

I think due to this: https://github.com/nandorojo/solito/blob/master/example-monorepos/blank/apps/expo/package.json#L3 

I'm a total mono-repo / yarn noob, so I'm probably missing something really simple here. How do I upgrade or add a definition for the expo app with yarn?

**Comment by nandorojo** [comment]
thanks for your findings! could you open a draft PR by chance? maybe we should rename `app` to something like `@my/app` so there are certainly no conflicts.

as for the dependencies, you should just update them in the respective package.json files and then run `yarn` from the root. 

we probably need a `react` resolution in the root package.json to fix it to `17.0.2`.

monorepos are hard…

**Comment by nandorojo** [comment]
try `yarn why expo-linking` to diagnose the issue

**Comment by jonsherrard** [comment]
Draft PR for Expo 45 is here: https://github.com/nandorojo/solito/pull/102

**Comment by nandorojo** [comment]
FWIW, I have expo 45 working in our monorepo, I just haven’t had time to do it in the solito example. At this point, I’ll probably just skip over to SDK 46.

**Comment by WillenOLeal** [comment]
@nandorojo I created a PR for upgrading the Solito monorepo to the Expo SDK 46 and Next.js 12.2.x #120

**Comment by JinbeiStudio** [comment]
I tried to upgrade to Expo SDK 46, but I have this error using the push method of the router, any clue ?

```
%s%s, TypeError: undefined is not an object (evaluating 'this.emitter'), 
    in LoginForm (created by Login)
    in Login (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
```

**Comment by nandorojo** [comment]
Could you refer to the PR? Seems like you're getting this issue using React Navigation's native stack. Is that a Solito error? Seems to me like it's using an old React Native version or something.
